baseURL = "https://bsch0111.github.io/"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
languageCode = "ko-kr"
defaultContentLanguage = "en-us"

# Enable Disqus
disqusShortname = "bsch0111-github-io"

# Google Analytics
# googleAnalytics = "UA-123-45"

[params]
title = "morgan's 블로그"
author = "morgan | Blog"
description = "간단하게 올리는 블로그 | bsch0111@naver.com"
profilePicture = "images/profile.jpg"
favicon = "favicons/"
keywords = ""
mainSections = ["post"]



## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/bsch0111/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:bsch0111@naver.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"
  

